# Generated by Django 5.0.1 on 2024-06-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ceeated',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='No description available', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media/upload'),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
