# Generated by Django 5.0.1 on 2024-06-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_just',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
