# Generated by Django 5.0.1 on 2024-06-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_item_price_just_item_loop_just'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='stati/images'),
        ),
    ]
